### ISSUE TITLE
 Peer-to-peer code review dd 05.11.2021

### ISSUE THREAD

**Issue by ghost** [IbrohimRasulov/to-do-list#5]
## HIGHLIGHTS 
- All functions seem to be working as expecting 
- Documentation is managed at a high level 
## SUGGESTIONS 
- You seem to have used many display flex, one global class of d-flex with the property 
- It is also great to reset the default style of the browser via using the HTML and * atributes

**Comment by piero-vic** [comment]
I will suggest to update the link to the live demo.

**Comment by IbrohimRasulov** [comment]
Thanks to all who gave suggestions. These help me to improve my project.
