### ISSUE TITLE
Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by codepantha** [IbrohimRasulov/To-Do-list#6]
## Hi @IbrohimRasulov 👋 👋 
You have a beautiful project.
### Things to highlight: 👇 
- Professional README.md ✔️ 
- Clean UI ✔️ 
- Drag and Drop functionality works really well ✔️ 
### Suggestions to hopefully make your code better:
- I noticed that you use spaces sparingly in your code. Any reason for this in particular? I believe if you have spacing in your code, you will be able to separate your thoughts more clearly and make your code more readable. What do you think?

Here's an example of what I'm talking about:
https://github.com/IbrohimRasulov/To-Do-list/blob/63727c023752be80ec399502b911878ef41dafa9/src/index.js#L59-L68

**Thanks for sharing your code**
### Cheers and happy coding 🎉 🎉

**Comment by IbrohimRasulov** [comment]
Thanks @ codepantherr, I really appreciate your suggestions. I totally agree with what you said, I try to fix the issue!
